# Generated by Django 4.2.6 on 2023-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ceo", "FOUNDER & CEO"),
                            ("vp", "FOUNDER, VP"),
                            ("editor", "EDITOR STAFF"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("business", "BUSINESS"),
                    ("culture", "CULTURE"),
                    ("celebrity", "CELEBRITY"),
                    ("design", "DESIGN"),
                    ("food", "FOOD"),
                    ("lifestyle", "LIFESTYLE"),
                    ("politics", "POLITICS"),
                    ("sports", "SPORTS"),
                    ("startups", "STARTUPS"),
                    ("tech", "TECH"),
                    ("travel", "TRAVEL"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(default="default", upload_to=""),
        ),
    ]
