# Generated by Django 4.2.6 on 2023-11-18 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
