# Generated by Django 4.2.6 on 2023-11-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("business", "BUSINESS"),
                    ("culture", "CULTURE"),
                    ("celebrity", "CELEBRITY"),
                    ("design", "DESIGN"),
                    ("food", "FOOD"),
                    ("lifestyle", "LIFESTYLE"),
                    ("politics", "POLITICS"),
                    ("sports", "SPORTS"),
                    ("startups", "STARTUPS"),
                    ("tech", "TECH"),
                    ("travel", "TRAVEL"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="pics",
            field=models.ImageField(blank=True, null=True, upload_to="team/"),
        ),
    ]
