# Generated by Django 4.2.6 on 2023-11-19 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_category_alter_post_slug_alter_team_pics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
