# Generated by Django 4.2.6 on 2023-11-19 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0008_remove_comment_post_remove_post_author_delete_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ceo", "FOUNDER & CEO"),
                            ("vp", "FOUNDER, VP"),
                            ("editor", "EDITOR STAFF"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("pics", models.ImageField(upload_to="team/")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("business", "BUSINESS"),
                            ("culture", "CULTURE"),
                            ("celebrity", "CELEBRITY"),
                            ("design", "DESIGN"),
                            ("food", "FOOD"),
                            ("lifestyle", "LIFESTYLE"),
                            ("politics", "POLITICS"),
                            ("sports", "SPORTS"),
                            ("startups", "STARTUPS"),
                            ("tech", "TECH"),
                            ("travel", "TRAVEL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("img", models.ImageField(upload_to="images/")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("published", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("text", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_comment", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
